fix(example): Compile format & lint examples in CI (#21)
* Fix example

* Skip the device advisor test in CI for now

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,14 +6,29 @@ on:
       - master
   pull_request:
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
 jobs:
-  cancel_previous_runs:
-    name: Cancel previous runs
+  build:
+    name: Build
     runs-on: ubuntu-latest
     steps:
-      - uses: styfle/cancel-workflow-action@0.4.1
-        with:
-          access_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Checkout source code
+        uses: actions/checkout@v4
+
+      - uses: dsherret/rust-toolchain-file@v1
+
+      - name: Build (library)
+        run: cargo build --all --target thumbv7em-none-eabihf
+
+      - name: Build (examples)
+        run: |
+          for EXAMPLE in $(ls examples);
+          do
+            (cd examples/$EXAMPLE && cargo build)
+          done
 
   test:
     name: Test
@@ -26,9 +41,6 @@ jobs:
         uses: actions/checkout@v4
 
       - uses: dsherret/rust-toolchain-file@v1
-
-      - name: Build
-        run: cargo build --all --target thumbv7em-none-eabihf
 
       - name: Test
         run: cargo test --features "log,${{ matrix.mqtt_version }}"
@@ -45,70 +57,70 @@ jobs:
       - name: Fuzz (PubSub)
         run: ./fuzz.sh
 
-  device_advisor:
-    name: AWS IoT Device Advisor
-    runs-on: ubuntu-latest
-    needs: test
-    env:
-      AWS_EC2_METADATA_DISABLED: true
-      AWS_DEFAULT_REGION: ${{ secrets.MGMT_AWS_DEFAULT_REGION }}
-      AWS_ACCESS_KEY_ID: ${{ secrets.MGMT_AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.MGMT_AWS_SECRET_ACCESS_KEY }}
-      SUITE_ID: 1gaev57dq6i5
-      THING_ARN: arn:aws:iot:eu-west-1:411974994697:thing/embedded-mqtt
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
+  # device_advisor:
+  #   name: AWS IoT Device Advisor
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   env:
+  #     AWS_EC2_METADATA_DISABLED: true
+  #     AWS_DEFAULT_REGION: ${{ secrets.MGMT_AWS_DEFAULT_REGION }}
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.MGMT_AWS_ACCESS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.MGMT_AWS_SECRET_ACCESS_KEY }}
+  #     SUITE_ID: 1gaev57dq6i5
+  #     THING_ARN: arn:aws:iot:eu-west-1:411974994697:thing/embedded-mqtt
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
 
-      - uses: dsherret/rust-toolchain-file@v1
+  #     - uses: dsherret/rust-toolchain-file@v1
 
-      - name: Get AWS_HOSTNAME
-        id: hostname
-        run: |
-          hostname=$(aws iotdeviceadvisor get-endpoint --thing-arn ${{ env.THING_ARN }} --output text --query endpoint)
-          ret=$?
-          echo "::set-output name=AWS_HOSTNAME::$hostname"
-          exit $ret
+  #     - name: Get AWS_HOSTNAME
+  #       id: hostname
+  #       run: |
+  #         hostname=$(aws iotdeviceadvisor get-endpoint --thing-arn ${{ env.THING_ARN }} --output text --query endpoint)
+  #         ret=$?
+  #         echo "::set-output name=AWS_HOSTNAME::$hostname"
+  #         exit $ret
 
-      - name: Build test binary
-        env:
-          AWS_HOSTNAME: ${{ steps.hostname.outputs.AWS_HOSTNAME }}
-        run: cargo build --features=log --example aws_device_advisor --release
+  #     - name: Build test binary
+  #       env:
+  #         AWS_HOSTNAME: ${{ steps.hostname.outputs.AWS_HOSTNAME }}
+  #       run: cargo build --features=log --example aws_device_advisor --release
 
-      - name: Start test suite
-        id: test_suite
-        run: |
-          suite_id=$(aws iotdeviceadvisor start-suite-run --suite-definition-id ${{ env.SUITE_ID }} --suite-run-configuration "primaryDevice={thingArn=${{ env.THING_ARN }}},parallelRun=true" --output text --query suiteRunId)
-          ret=$?
-          echo "::set-output name=SUITE_RUN_ID::$suite_id"
-          exit $ret
+  #     - name: Start test suite
+  #       id: test_suite
+  #       run: |
+  #         suite_id=$(aws iotdeviceadvisor start-suite-run --suite-definition-id ${{ env.SUITE_ID }} --suite-run-configuration "primaryDevice={thingArn=${{ env.THING_ARN }}},parallelRun=true" --output text --query suiteRunId)
+  #         ret=$?
+  #         echo "::set-output name=SUITE_RUN_ID::$suite_id"
+  #         exit $ret
 
-      - name: Execute test binary
-        id: binary
-        env:
-          DEVICE_ADVISOR_PASSWORD: ${{ secrets.DEVICE_ADVISOR_PASSWORD }}
-          RUST_LOG: trace
-        run: |
-          nohup ./target/release/examples/aws_device_advisor > device_advisor_integration.log &
-          echo "::set-output name=PID::$!"
+  #     - name: Execute test binary
+  #       id: binary
+  #       env:
+  #         DEVICE_ADVISOR_PASSWORD: ${{ secrets.DEVICE_ADVISOR_PASSWORD }}
+  #         RUST_LOG: trace
+  #       run: |
+  #         nohup ./target/release/examples/aws_device_advisor > device_advisor_integration.log &
+  #         echo "::set-output name=PID::$!"
 
-      - name: Monitor test run
-        run: |
-          chmod +x ./scripts/da_monitor.sh
-          echo ${{ env.SUITE_ID }} ${{ steps.test_suite.outputs.SUITE_RUN_ID }} ${{ steps.binary.outputs.PID }}
-          ./scripts/da_monitor.sh ${{ env.SUITE_ID }} ${{ steps.test_suite.outputs.SUITE_RUN_ID }} ${{ steps.binary.outputs.PID }}
+  #     - name: Monitor test run
+  #       run: |
+  #         chmod +x ./scripts/da_monitor.sh
+  #         echo ${{ env.SUITE_ID }} ${{ steps.test_suite.outputs.SUITE_RUN_ID }} ${{ steps.binary.outputs.PID }}
+  #         ./scripts/da_monitor.sh ${{ env.SUITE_ID }} ${{ steps.test_suite.outputs.SUITE_RUN_ID }} ${{ steps.binary.outputs.PID }}
 
-      - name: Kill test binary process
-        if: ${{ always() }}
-        run: kill ${{ steps.binary.outputs.PID }} || true
+  #     - name: Kill test binary process
+  #       if: ${{ always() }}
+  #       run: kill ${{ steps.binary.outputs.PID }} || true
 
-      - name: Log binary output
-        if: ${{ always() }}
-        run: cat device_advisor_integration.log
+  #     - name: Log binary output
+  #       if: ${{ always() }}
+  #       run: cat device_advisor_integration.log
 
-      - name: Stop test suite
-        if: ${{ failure() }}
-        run: aws iotdeviceadvisor stop-suite-run --suite-definition-id ${{ env.SUITE_ID }} --suite-run-id ${{ steps.test_suite.outputs.SUITE_RUN_ID }}
+  #     - name: Stop test suite
+  #       if: ${{ failure() }}
+  #       run: aws iotdeviceadvisor stop-suite-run --suite-definition-id ${{ env.SUITE_ID }} --suite-run-id ${{ steps.test_suite.outputs.SUITE_RUN_ID }}
 
   rustfmt:
     name: rustfmt
@@ -119,8 +131,15 @@ jobs:
         uses: actions/checkout@v4
       - uses: dsherret/rust-toolchain-file@v1
 
-      - name: Run rustfmt
+      - name: Run rustfmt (library)
         run: cargo fmt --all -- --check --verbose
+
+      - name: Run rustfmt (examples)
+        run: |
+          for EXAMPLE in $(ls examples);
+          do
+            (cd examples/$EXAMPLE && cargo fmt --all -- --check --verbose)
+          done
 
   clippy:
     name: clippy
@@ -133,5 +152,12 @@ jobs:
         uses: actions/checkout@v4
       - uses: dsherret/rust-toolchain-file@v1
 
-      - name: Run clippy
+      - name: Run clippy (library)
         run: cargo clippy --features "log" -- ${{ env.CLIPPY_PARAMS }}
+
+      - name: Run clippy (examples)
+        run: |
+          for EXAMPLE in $(ls examples);
+          do
+            (cd examples/$EXAMPLE && cargo clippy -- ${{ env.CLIPPY_PARAMS }})
+          done
